// LeadManagement

export enum ActionType {
  GET_ALL_ANALYSIS = 'GET_ALL_ANALYSIS',
  GET_ALL_COUNTRIES = 'GET_ALL_COUNTRIES',
  GET_ALL_CAMPS = 'GET_ALL_CAMPS',
  GET_ALL_SCHOOLS = 'GET_ALL_SCHOOLS',
  FILTERED_DATA = 'FILTERED_DATA',
  FILTER_STATE = 'FILTER_STATE',
  SELECTED_SCHOOLS = 'SELECTED_SCHOOLS',
}
// export const GET_LEAD_MANAGEMENT_BY_ID = 'GET_LEAD_MANAGEMENT_BY_ID'
